defaults:
  - dataset: lichess-uci-201301
  - llm: chessGPT_d12

run:
  debug: false
  report_to: wandb # add
  name: ${now:%Y-%m-%d}/${now:%H-%M-%S}
  model_dir: models/${run.name}

training: # Use any arguments from the Hugging Face TrainerArguments class
  _target_: transformers.TrainingArguments
  report_to: ${run.report_to}
  auto_find_batch_size: true
  bf16: true
  save_total_limit: 1
  torch_compile: false
  run_name: ${run.name}
  output_dir: ${run.model_dir}
